name: Cypress Tests

on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
      - '.github/workflows/cypress.yml'

permissions:
  contents: read

jobs:
  cypress-run:
    permissions:
      actions: read  # for cypress-io/github-action to correctly identify workflow run
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    # Runs tests in parallel with matrix strategy https://docs.cypress.io/guides/guides/parallelization
    # https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs
    # Also see warning here https://github.com/cypress-io/github-action#parallel
    strategy:
      fail-fast: false # https://github.com/cypress-io/github-action/issues/48
      matrix:
        containers: [1] # No parallelization
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: 'Checking Out Code'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1

      - name: Get yarn cache directory path
        working-directory: frontend
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3.3.2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: 'Installing Dependencies'
        working-directory: frontend/testing/cypress
        run: yarn install --immutable --inline-builds
        env:
          YARN_ENABLE_GLOBAL_CACHE: 'false'
          YARN_NM_MODE: 'hardlinks-local'
          HUSKY: '0'

      - name: Wait for deploy to environment
        run: sleep 6m
        shell: bash

      - name: Cypress run
        uses: cypress-io/github-action@248bde77443c376edc45906ede03a1aba9da0462 # v5.8.4
        with:
          install: false
          working-directory: frontend/testing/cypress
          env: environment=dev,autoTestUserPwd=${{ secrets.AUTO_TEST_USER_PWD }},accessToken=${{ secrets.AUTO_TEST_USER_TOKEN_DEV }}
          spec: src/integration/studio/*.js
          record: true
          parallel: false
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Store artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        if: failure()
        with:
          name: cypress-screenshots
          path: frontend/testing/cypress/screenshots
