name: Frontend Tests

on:
  push:
    paths:
      - 'frontend/**'
      - '!frontend/testing/cypress/**'
      - 'testdata/**'
      - '.github/workflows/frontend-unit-tests.yml'
      - 'package.json'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  CYPRESS_INSTALL_BINARY: 0

jobs:
  codeql:
    name: 'CodeQL'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: 'Checking Out Code'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: 'Initialize CodeQL'
        uses: github/codeql-action/init@ddccb873888234080b77e9bc2d4764d5ccaaccf9 # v2.21.9
        with:
          languages: javascript
          queries: +security-and-quality
          config-file: .github/codeql/codeql-config.yml

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@ddccb873888234080b77e9bc2d4764d5ccaaccf9 # v2.21.9
        with:
          category: '/language:javascript'

  typecheck:
    name: 'Typechecking and linting'
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: 'Checking Out Code'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: 'Installing Dependencies'
        uses: ./.github/actions/yarn-install

      - name: 'Doing the typecheck'
        run: yarn typecheck

      - name: 'Running Eslint'
        run: yarn lint

  test:
    name: 'Testing'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: 'Checking Out Code'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: 'Installing Dependencies'
        uses: ./.github/actions/yarn-install

      - name: 'Running Unit Tests'
        run: yarn test:ci

      - name: 'Upload coverage reports to Codecov'
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          directory: frontend/coverage
          fail_ci_if_error: true

  build:
    name: 'Building'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
        with:
          egress-policy: audit

      - name: 'Checking Out Code'
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
        with:
          fetch-depth: 0

      - name: 'Installing Dependencies'
        uses: ./.github/actions/yarn-install

      - name: 'Building'
        run: yarn build
