name: PDF Scan

on:
  schedule:
    - cron: '21 8 * * 1,4'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423 # v2.6.0
      with:
        egress-policy: audit

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
    - name: Build the Docker image
      run: docker build src/Altinn.Platform/Altinn.Platform.PDF --file src/Altinn.Platform/Altinn.Platform.PDF/Dockerfile --tag altinn-pdf:${{github.sha}}

    - uses: Azure/container-scan@f9af925b897d8af5f7e0026b8bca9346261abc93 # v0.1
      env:
        # See https://github.com/goodwithtech/dockle/issues/188
        DOCKLE_HOST: "unix:///var/run/docker.sock"
      with:
        image-name: altinn-pdf:${{ github.sha }}
